/*
=========================================================
Sales Analysis
=========================================================
*/

-- What is the total revenue generated?
select round(sum(payment_value),2) as Total_revenue from olist_order_payments;
=========================================================
-- What is the total revenue generated in every month?
select date_format(p.order_purchase_timestamp,'%m') as Month,
round(sum(o.payment_value),2) As Total_revenue
from olist_order_payments o
join olist_orders p
on o.order_id=p.order_id
group by Month 
order by Total_revenue;
=========================================================
-- What is the total revenue generated by each state?
select c.customer_state, round(sum(d.price),2) as Total_revenue
from olist_customers c
join olist_orders o
on c.customer_id=o.customer_id
join olist_order_items_dataset d
on d.order_id=o.order_id
group by c.customer_state
order by Total_revenue desc;
=========================================================
-- What is the total revenue generated by each category?
select p.product_category_name , round(sum(d.price),2) as Total
from olist_products p
join olist_order_items_dataset d
on d.product_id=p.product_id
group by p.product_category_name
order by Total;
=========================================================
-- What is the revenue generated by sellers?
select seller_id, round(sum(price),2) as Total_revenue
from olist_order_items_dataset
group by seller_id
order by Total_revenue;
=========================================================
-- What is the average order value?
select round(sum(price)/count(distinct order_id),2) as Average_Order from olist_order_items_dataset;
=========================================================
-- Top 20 Most Expensive Products
select product_id, price from olist_order_items_dataset order by price desc limit 20;
=========================================================
-- Which products generated the highest revenue?
select product_id, round(sum(price),2) as Total
from olist_order_items_dataset
group by product_id 
order by Total desc limit 20;
=========================================================
-- Which products sold the most units?
select product_id, count(*) as Total_count
from olist_order_items_dataset
group by product_id
order by Total_count desc;
=========================================================
-- What is the highest freight cost charged?
SELECT MAX(freight_value)
FROM olist_order_items_dataset;
=========================================================
-- What is the average freight cost?
select avg(freight_value) as Average_freight from olist_order_items_dataset;
=========================================================
-- What is the Month-over-Month (MoM) Revenue Growth?
select month, monthly_revenue,LAG(monthly_revenue) over(order by month) as previous_month from(
select date_format(o.order_purchase_timestamp,'%Y-%m') as month,
round(sum(d.price),2) as monthly_revenue
from olist_orders o
join olist_order_items_dataset d
on o.order_id=d.order_id
group by month) as monthly_sales;
=========================================================
-- What is running monthly revenue?
select month,monthly_revenue, sum(monthly_revenue) OVER(
order by month
)  as running_revenue from(
select date_format(o.order_purchase_timestamp,'%Y-%m') as month, round(sum(d.price)) as monthly_revenue
from olist_orders o
join olist_order_items_dataset d
on o.order_id=d.order_id
group by month) as monthly_sales;
=========================================================
-- What is the 3-month moving average of monthly sales?
select month, monthly_revenue, round(avg(monthly_revenue) over(order by month 
rows between 2 preceding and current row),2) as running_revenue from(
select date_format(o.order_purchase_timestamp,'%Y-%m') as month, round(sum(d.price),2) as monthly_revenue
from olist_orders o
join olist_order_items_dataset d
on o.order_id=d.order_id
group by month) as monthly_sales;
